"""initial_schema

Revision ID: 2f49ebb7dd38
Revises: 
Create Date: 2026-06-24 10:59:04.270679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f49ebb7dd38'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('partners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('document', sa.String(length=18), nullable=False),
    sa.Column('document_type', sa.Enum('CPF', 'CNPJ', name='document_type_enum'), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('segment', sa.String(length=100), nullable=True),
    sa.Column('company_name', sa.String(length=200), nullable=True),
    sa.Column('utm_code', sa.String(length=20), nullable=False),
    sa.Column('referral_url', sa.String(length=500), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'SUSPENDED', 'TERMINATED', name='partner_status_enum'), nullable=False),
    sa.Column('hashed_password', sa.String(length=200), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('bank_info', sa.JSON(), nullable=True),
    sa.Column('term_accepted_at', sa.DateTime(), nullable=True),
    sa.Column('term_ip', sa.String(length=45), nullable=True),
    sa.Column('term_version', sa.String(length=20), nullable=True),
    sa.Column('documents', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('utm_code')
    )
    op.create_table('in_app_notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.String(length=120), nullable=False),
    sa.Column('type', sa.Enum('NEW_LEAD', 'COMMISSION_UPDATED', 'PROPERTY_STATUS', name='notification_type_enum'), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.String(length=500), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['partners.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id')
    )
    with op.batch_alter_table('in_app_notifications', schema=None) as batch_op:
        batch_op.create_index('ix_notifications_user_created', ['user_id', 'created_at'], unique=False)
        batch_op.create_index('ix_notifications_user_read', ['user_id', 'read_at'], unique=False)

    op.create_table('leads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('partner_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('cpf', sa.String(length=11), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('address_street', sa.String(length=200), nullable=True),
    sa.Column('address_number', sa.String(length=20), nullable=True),
    sa.Column('address_complement', sa.String(length=100), nullable=True),
    sa.Column('address_city', sa.String(length=100), nullable=True),
    sa.Column('address_state', sa.String(length=2), nullable=True),
    sa.Column('address_zip', sa.String(length=8), nullable=True),
    sa.Column('utm_code', sa.String(length=20), nullable=False),
    sa.Column('utm_source', sa.String(length=100), nullable=True),
    sa.Column('utm_medium', sa.String(length=100), nullable=True),
    sa.Column('utm_campaign', sa.String(length=100), nullable=True),
    sa.Column('lgpd_consent', sa.Boolean(), nullable=False),
    sa.Column('lgpd_consent_at', sa.DateTime(), nullable=True),
    sa.Column('lgpd_consent_ip', sa.String(length=45), nullable=True),
    sa.Column('status', sa.Enum('NEW', 'CONTACTED', 'QUALIFIED', 'CONVERTED', 'EXPIRED', 'DISQUALIFIED', name='lead_status_enum'), nullable=False),
    sa.Column('attribution_expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.create_index('ix_lead_address', ['address_street', 'address_number', 'address_city'], unique=False)
        batch_op.create_index('ix_lead_phone', ['phone'], unique=False)

    op.create_table('materials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('category', sa.Enum('ART', 'TEXT', 'PRESENTATION', name='material_category_enum'), nullable=False),
    sa.Column('status', sa.Enum('PUBLISHED', 'ARCHIVED', name='material_status_enum'), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('file_url', sa.String(length=1000), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_mime_type', sa.String(length=120), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('created_by_partner_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_partner_id'], ['partners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('material_downloads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('partner_id', sa.Integer(), nullable=False),
    sa.Column('downloaded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('material_downloads', schema=None) as batch_op:
        batch_op.create_index('ix_material_downloads_material', ['material_id'], unique=False)
        batch_op.create_index('ix_material_downloads_partner', ['partner_id'], unique=False)

    op.create_table('properties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('partner_id', sa.Integer(), nullable=False),
    sa.Column('owner_name', sa.String(length=200), nullable=False),
    sa.Column('owner_document', sa.String(length=18), nullable=False),
    sa.Column('address_street', sa.String(length=200), nullable=False),
    sa.Column('address_number', sa.String(length=20), nullable=False),
    sa.Column('address_complement', sa.String(length=100), nullable=True),
    sa.Column('address_city', sa.String(length=100), nullable=False),
    sa.Column('address_state', sa.String(length=2), nullable=False),
    sa.Column('address_zip', sa.String(length=8), nullable=False),
    sa.Column('contract_model', sa.Enum('A', 'B', 'C', name='contract_model_enum'), nullable=False),
    sa.Column('model_a_setup_fee', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('model_a_revenue_pct', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('model_b_setup_fee', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('model_b_fixed_monthly', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('model_b_revenue_pct', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('model_c_first_allocation', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('model_c_ongoing_pct', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('setup_fee_paid', sa.Boolean(), nullable=False),
    sa.Column('setup_fee_paid_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('LEAD', 'PROPOSAL_SENT', 'CONTRACT_SIGNED', 'ONBOARDING', 'OPERATIONAL', 'CANCELLED', name='property_status_enum'), nullable=False),
    sa.Column('operational_since', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('revenue_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('reference_year', sa.Integer(), nullable=False),
    sa.Column('reference_month', sa.Integer(), nullable=False),
    sa.Column('gross_revenue', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('wecare_admin_fee', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('owner_payout', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('is_first_complete_month', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('property_id', 'reference_year', 'reference_month', name='uq_revenue_record_period')
    )
    op.create_table('commissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('partner_id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('revenue_record_id', sa.Integer(), nullable=False),
    sa.Column('contract_model', sa.Enum('A', 'B', 'C', name='contract_model_enum'), nullable=False),
    sa.Column('commission_base', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('commission_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'AWAITING_NFSE', 'APPROVED', 'PAID', 'CANCELLED', name='commission_status_enum'), nullable=False),
    sa.Column('cancellation_reason', sa.Enum('OWNER_CANCELLED', 'PROPERTY_NEVER_OPERATED', 'FRAUD', 'CHARGEBACK', name='cancellation_reason_enum'), nullable=True),
    sa.Column('payment_due_date', sa.Date(), nullable=False),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('nfse_number', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.ForeignKeyConstraint(['revenue_record_id'], ['revenue_records.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('revenue_record_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('commissions')
    op.drop_table('revenue_records')
    op.drop_table('properties')
    with op.batch_alter_table('material_downloads', schema=None) as batch_op:
        batch_op.drop_index('ix_material_downloads_partner')
        batch_op.drop_index('ix_material_downloads_material')

    op.drop_table('material_downloads')
    op.drop_table('materials')
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.drop_index('ix_lead_phone')
        batch_op.drop_index('ix_lead_address')

    op.drop_table('leads')
    with op.batch_alter_table('in_app_notifications', schema=None) as batch_op:
        batch_op.drop_index('ix_notifications_user_read')
        batch_op.drop_index('ix_notifications_user_created')

    op.drop_table('in_app_notifications')
    op.drop_table('partners')
    # ### end Alembic commands ###
