"""add_crm_clients

Revision ID: 9c1aca572ad1
Revises: 2f49ebb7dd38
Create Date: 2026-06-25 22:20:57.811332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c1aca572ad1'
down_revision: Union[str, Sequence[str], None] = '2f49ebb7dd38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crm_clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo_wecare', sa.String(length=20), nullable=False),
    sa.Column('codigo_cliente', sa.String(length=20), nullable=False),
    sa.Column('nome_cliente', sa.String(length=200), nullable=False),
    sa.Column('nome_imovel', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=254), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('cidade', sa.String(length=100), nullable=True),
    sa.Column('estado', sa.String(length=2), nullable=True),
    sa.Column('canal_aquisicao', sa.String(length=100), nullable=False),
    sa.Column('partner_id', sa.Integer(), nullable=True),
    sa.Column('fase_atual', sa.Enum('1_lead', '2_reuniao', '3_proposta_contrato', '4_aguardando_docs', '5_assinatura', 'operacao', 'perdido', name='crm_fase_enum'), nullable=False),
    sa.Column('proxima_acao', sa.String(length=500), nullable=True),
    sa.Column('prazo', sa.Date(), nullable=True),
    sa.Column('notas', sa.String(length=5000), nullable=True),
    sa.Column('tipo_imovel', sa.String(length=100), nullable=True),
    sa.Column('capacidade_hospedes', sa.Integer(), nullable=True),
    sa.Column('valor_setup', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('percentual_admin', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('contrato_assinado', sa.Boolean(), nullable=False),
    sa.Column('lead_entrada', sa.Date(), nullable=True),
    sa.Column('lead_saida', sa.Date(), nullable=True),
    sa.Column('reuniao_entrada', sa.Date(), nullable=True),
    sa.Column('reuniao_saida', sa.Date(), nullable=True),
    sa.Column('proposta_entrada', sa.Date(), nullable=True),
    sa.Column('proposta_saida', sa.Date(), nullable=True),
    sa.Column('docs_entrada', sa.Date(), nullable=True),
    sa.Column('docs_saida', sa.Date(), nullable=True),
    sa.Column('assinatura_entrada', sa.Date(), nullable=True),
    sa.Column('assinatura_saida', sa.Date(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo_cliente'),
    sa.UniqueConstraint('codigo_wecare')
    )
    with op.batch_alter_table('crm_clients', schema=None) as batch_op:
        batch_op.create_index('ix_crm_clients_fase', ['fase_atual'], unique=False)
        batch_op.create_index('ix_crm_clients_partner', ['partner_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crm_clients', schema=None) as batch_op:
        batch_op.drop_index('ix_crm_clients_partner')
        batch_op.drop_index('ix_crm_clients_fase')

    op.drop_table('crm_clients')
    # ### end Alembic commands ###
